server:
  port: 8004
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/ #\u6CE8\u518C\u4E2D\u5FC3\u5730\u5740
  instance:
    hostname: resource
spring:
  application:
    name: resource #\u670D\u52A1\u540D\u79F0
