server:
  port: 8003
  servlet:
    context-path: /api #所有请求都增加该前缀如https://localhost:8080/api
    #配置https
  ssl:
    enabled: true
    #文件
    key-store: classpath:aenlly.jks
    #密码,一个是文件密码，一个是密匙密码
    key-password: xtx6nRj2
    key-store-password: xtx6nRj2
    #密匙库类型，tomcat只支持PKCS12和JKS
    key-store-type: JKS

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/ #注册中心地址
  instance:
    hostname: admin
spring:
  application:
    name: admin #服务名称
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/rcc
    druid:
      test-while-idle: true #获取连接时检查连接是否有效
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 524288000 #单次文件最大500mb
      max-request-size: 524288000 #总数据大小
#  mvc:
#    static-path-pattern: /** #网页访问的路径
#  web:
#    resources:
#      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${upload.path} #mvc配置类二选一，
#      #项目地址classpath：地址
#      #默认开放classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
#      #本地的资源地址file:本地地址
#upload: #上传的路径
#  path: C:/aenlly/static #远程路径，下面位本地调试路径

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 输出日志
  type-aliases-package: com.aenlly.rcc.entity
  type-enums-package: com.aenlly.rcc.enums #扫描枚举
