server:
  port: 8003

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8001/eureka/ #注册中心地址
  instance:
    hostname: admin
spring:
  profiles:
    active: dev # 使用dev配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 524288000 #单次文件最大500mb
      max-request-size: 524288000 #总数据大小
#  mvc:
#    static-path-pattern: /** #网页访问的路径
#  web:
#    resources:
#      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/ #mvc配置类二选一，,file:${upload.path}
#      #项目地址classpath：地址
#      #默认开放classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
#      #本地的资源地址file:本地地址
#upload: #上传的路径
#  path: C:/aenlly/static #远程路径，下面位本地调试路径

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 输出日志
  type-aliases-package: com.aenlly.rcc.entity
  type-enums-package: com.aenlly.rcc.enums #扫描枚举
